import { TPFDetails, DocumentData, DocumentType } from '../types/document';

// Fixed True Path Foundation details as in TPFINV_004
export const TPF_FIXED_DETAILS: TPFDetails = {
  name: 'TRUE PATH FOUNDATION',
  pan: 'AAJCT7092M',
  addressLine1: '229A, DDA FLATS,',
  addressLine2: 'POCKET - 12, JASOLA,',
  cityStatePin: 'NEW DELHI - 110025',
};

// Default Editable Sender Details from TPFINV_004
export const DEFAULT_SENDER_DETAILS = {
  name: 'AQUIB MOHAMMED ALI HINGWALA',
  pan: 'AVDCSH8283A',
  gstin: '',
  addressLine1: 'C-9, Mukund Nagar, Marol Pipe Line,',
  addressLine2: 'Andheri East',
  city: 'Mumbai',
  state: 'Maharashtra',
  pinCode: '400059',
  mobile: '+91 91678 33311',
  email: 'aca@gmail.com.com',
};

export const DEFAULT_TERMS: Record<DocumentType, string[]> = {
  INVOICE: [
    'Payment received in full. Thank you for your business!',
    'This invoice serves as an official receipt of payment received.',
    'This is a computer generated invoice, signature not required.',
  ],
  CHALLAN: [
    'Payment is currently due and payable on or before the due date.',
    'Make all checks/transfers payable to the bank account credentials listed above.',
    'Please mention Challan Number in payment remarks for verification.',
  ],
  QUOTATION: [
    'Quotation valid for 15 days from the date of issue.',
    'If you approve this quotation, work will begin upon written approval and agreed terms.',
    'This is a proposed cost estimate and not a demand for payment or receipt.',
  ],
};

export const DEFAULT_NOTES: Record<DocumentType, string> = {
  INVOICE: 'RECEIPT CONFIRMATION: Payment has been received in full for the items listed below. No balance is due.',
  CHALLAN: 'PAYMENT DEMAND: This document shows the total amount currently payable. Please pay on or before the due date.',
  QUOTATION: 'PROPOSED COST ESTIMATE: This proposal details the estimated costs for approval. Services will be rendered upon agreement.',
};

export const INITIAL_SAMPLE_DATA: Record<DocumentType, DocumentData> = {
  INVOICE: {
    meta: {
      documentType: 'INVOICE',
      documentNumber: '004',
      issueDate: '2026-02-25',
      dueDate: '2026-02-25',
      referenceNo: '',
      subject: 'UI/UX Design & Development Services',
      notes: DEFAULT_NOTES.INVOICE,
      terms: DEFAULT_TERMS.INVOICE,
    },
    sender: DEFAULT_SENDER_DETAILS,
    billTo: {
      name: TPF_FIXED_DETAILS.name,
      pan: TPF_FIXED_DETAILS.pan,
      gstin: '',
      addressLine1: TPF_FIXED_DETAILS.addressLine1,
      addressLine2: TPF_FIXED_DETAILS.addressLine2,
      city: 'NEW DELHI',
      state: 'DELHI',
      pinCode: '110025',
      mobile: '',
      email: '',
    },
    shipTo: {
      name: TPF_FIXED_DETAILS.name,
      pan: TPF_FIXED_DETAILS.pan,
      gstin: '',
      addressLine1: TPF_FIXED_DETAILS.addressLine1,
      addressLine2: TPF_FIXED_DETAILS.addressLine2,
      city: 'NEW DELHI',
      state: 'DELHI',
      pinCode: '110025',
      mobile: '',
      email: '',
    },
    useSameShipTo: true,
    items: [
      {
        id: '1',
        name: 'Phase 1',
        description: 'Full UI approved by client.\nIncludes all user modules (Donor, Member, Volunteer, Beneficiary, Employee)), Donation & Campaign systems, Fund allocation, Tax reports, Zakat calculator etc',
        quantity: 1,
        unitPrice: 33750,
        total: 33750,
      },
      {
        id: '2',
        name: 'Phase 2',
        description: 'Backend and functionality added for all Phase 1 UI components',
        quantity: 1,
        unitPrice: 33750,
        total: 33750,
      },
      {
        id: '3',
        name: 'Phase 3',
        description: 'Final handover of the complete web application with all fully working modules from Phase 1 and Phase 2.',
        quantity: 1,
        unitPrice: 67500,
        total: 67500,
      },
    ],
    calculations: {
      subtotal: 135000,
      discountType: 'flat',
      discountValue: 0,
      discountAmount: 0,
      taxType: 'flat',
      taxValue: 0,
      taxAmount: 0,
      taxLabel: 'TAX',
      additionalCharges: 0,
      additionalChargesLabel: '',
      grandTotal: 135000,
      amountPaid: 135000,
      balancePayable: 0,
      paymentStatus: 'PAID',
    },
    paymentDetails: {
      accountName: 'Mr. Aquib Mohammed Ali Hingwala',
      bankName: 'SVC Co-operative Bank Ltd., Sakinaka, Mumbai (MH)',
      accountNumber: '300003000016361',
      ifscCode: 'SVCB0000007',
      showPaymentDetails: true,
    },
  },
  CHALLAN: {
    meta: {
      documentType: 'CHALLAN',
      documentNumber: '005',
      issueDate: '2026-02-25',
      dueDate: '2026-03-05',
      referenceNo: '',
      subject: 'Payment Demand for Web Application Phase 2',
      notes: DEFAULT_NOTES.CHALLAN,
      terms: DEFAULT_TERMS.CHALLAN,
    },
    sender: DEFAULT_SENDER_DETAILS,
    billTo: {
      name: TPF_FIXED_DETAILS.name,
      pan: TPF_FIXED_DETAILS.pan,
      gstin: '',
      addressLine1: TPF_FIXED_DETAILS.addressLine1,
      addressLine2: TPF_FIXED_DETAILS.addressLine2,
      city: 'NEW DELHI',
      state: 'DELHI',
      pinCode: '110025',
      mobile: '',
      email: '',
    },
    shipTo: {
      name: TPF_FIXED_DETAILS.name,
      pan: TPF_FIXED_DETAILS.pan,
      gstin: '',
      addressLine1: TPF_FIXED_DETAILS.addressLine1,
      addressLine2: TPF_FIXED_DETAILS.addressLine2,
      city: 'NEW DELHI',
      state: 'DELHI',
      pinCode: '110025',
      mobile: '',
      email: '',
    },
    useSameShipTo: true,
    items: [
      {
        id: '1',
        name: 'Phase 2',
        description: 'Backend and functionality added for all Phase 1 UI components',
        quantity: 1,
        unitPrice: 33750,
        total: 33750,
      },
    ],
    calculations: {
      subtotal: 33750,
      discountType: 'flat',
      discountValue: 0,
      discountAmount: 0,
      taxType: 'flat',
      taxValue: 0,
      taxAmount: 0,
      taxLabel: 'TAX',
      additionalCharges: 0,
      additionalChargesLabel: '',
      grandTotal: 33750,
      amountPaid: 0,
      balancePayable: 33750,
      paymentStatus: 'UNPAID',
    },
    paymentDetails: {
      accountName: 'Mr. Aquib Mohammed Ali Hingwala',
      bankName: 'SVC Co-operative Bank Ltd., Sakinaka, Mumbai (MH)',
      accountNumber: '300003000016361',
      ifscCode: 'SVCB0000007',
      showPaymentDetails: true,
    },
  },
  QUOTATION: {
    meta: {
      documentType: 'QUOTATION',
      documentNumber: '005',
      issueDate: '2026-02-25',
      dueDate: '2026-03-12',
      referenceNo: '',
      subject: 'Quotation for Web Portal Enhancement & Mobile App Integration',
      notes: DEFAULT_NOTES.QUOTATION,
      terms: DEFAULT_TERMS.QUOTATION,
    },
    sender: DEFAULT_SENDER_DETAILS,
    billTo: {
      name: TPF_FIXED_DETAILS.name,
      pan: TPF_FIXED_DETAILS.pan,
      gstin: '',
      addressLine1: TPF_FIXED_DETAILS.addressLine1,
      addressLine2: TPF_FIXED_DETAILS.addressLine2,
      city: 'NEW DELHI',
      state: 'DELHI',
      pinCode: '110025',
      mobile: '',
      email: '',
    },
    shipTo: {
      name: TPF_FIXED_DETAILS.name,
      pan: TPF_FIXED_DETAILS.pan,
      gstin: '',
      addressLine1: TPF_FIXED_DETAILS.addressLine1,
      addressLine2: TPF_FIXED_DETAILS.addressLine2,
      city: 'NEW DELHI',
      state: 'DELHI',
      pinCode: '110025',
      mobile: '',
      email: '',
    },
    useSameShipTo: true,
    items: [
      {
        id: '1',
        name: 'Phase 1',
        description: 'Full UI approved by client.\nIncludes all user modules (Donor, Member, Volunteer, Beneficiary, Employee)), Donation & Campaign systems',
        quantity: 1,
        unitPrice: 33750,
        total: 33750,
      },
      {
        id: '2',
        name: 'Phase 2',
        description: 'Backend and functionality added for all Phase 1 UI components',
        quantity: 1,
        unitPrice: 33750,
        total: 33750,
      },
    ],
    calculations: {
      subtotal: 67500,
      discountType: 'flat',
      discountValue: 0,
      discountAmount: 0,
      taxType: 'flat',
      taxValue: 0,
      taxAmount: 0,
      taxLabel: 'TAX',
      additionalCharges: 0,
      additionalChargesLabel: '',
      grandTotal: 67500,
      amountPaid: 0,
      balancePayable: 67500,
      paymentStatus: 'UNPAID',
    },
    paymentDetails: {
      accountName: 'Mr. Aquib Mohammed Ali Hingwala',
      bankName: 'SVC Co-operative Bank Ltd., Sakinaka, Mumbai (MH)',
      accountNumber: '300003000016361',
      ifscCode: 'SVCB0000007',
      showPaymentDetails: false,
    },
  },
};
